name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        docker build --build-arg OPENAI_API_KEY=$OPENAI_API_KEY -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG | tee push-output.txt
        export DIGEST=$(grep "digest: sha256:" push-output.txt | awk '{print $3}')
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV

    - name: Image digest
      run: echo "Image digest: ${{ env.DIGEST }}"
